version: '3.8'
services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "$DB_PORT:$DB_LOCAL_PORT"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+psycopg2://$DB_USER:$DB_PASSWORD@db:$DB_LOCAL_PORT/$DB_NAME"
      # Set your Reddit credentials here or use a .env file
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID}
      REDDIT_CLIENT_SECRET: ${REDDIT_CLIENT_SECRET}
      REDDIT_REFRESH_TOKEN: ${REDDIT_REFRESH_TOKEN}
      REDDIT_USER_AGENT: ${REDDIT_USER_AGENT}
      SUBREDDIT: ${SUBREDDIT}
    env_file:
      - .env
    restart: unless-stopped
    tty: true
# volumes:
#   db_data:
